version: "2"

services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8080:8912"
    links:
      - mongo
      - neo4j
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  neo4j:
    image: neo4j:2.3
    ports:
      - "7474:7474"
    volumes:
      - $HOME/neo4j/data:/data